spring:
  data:
    redis:
      host: 112.124.69.30
      port: 6379
      password: redis123
      lettuce:
        pool:
          max-active: 8
          min-idle: 0
          max-idle: 8
          max-wait: 100ms
